(define (domain domainName)
  (:requirements :derived-predicates :equality :negative-preconditions :numeric-fluents)
  (:predicates (notEquals ?a ?b)
               (totalTimeLesserThan10))
  (:functions (totalTime) - number)
  (:derived (notEquals ?a ?b)
            (not (= ?a ?b))
  )
  (:derived (totalTimeLesserThan10)
            (< (totalTime) 10)
  )
)