(define (domain domainName)
  (:requirements :typing :adl :fluents :preferences)
  (:constants constA)
  (:predicates (pred))
  (:functions (objFunc) - object)
  (:action actionName
    :parameters ()
    :precondition (and
                    (preference prefName (pred))
                    (pred)
                    (not (pred))
                    (and (pred) (pred))
                    (or (pred) (pred) (pred))
                    (imply (pred) (pred))
                    (forall (?x) (pred))
                    (exists (?x) (pred))
                    (<= (+ 3 8) 5)
                    (= (objFunc) constA)
                  )
  )
)
