(define (problem problemName)
  (:domain domainName)
  (:init (predA constA)
         (= objFunc constB)
  )
  (:goal (and
           (predA constA)
           (predA constB)
           (predB constA)
           (predB constB)
           (= objFunc constA)
         )
  )
)