(define (domain domainName)
  (:requirements :strips :adl)
  (:types typeA typeB)
  (:constants constA constB - typeA)
  (:predicates (predA ?aa) (predB ?aa))
  (:functions (funcA) (funcB ?aa) - number)
  (:constraints (always (pred ?aa)))
  (:action actionName
    :parameters (?aa)
    :precondition ()
    :effect ()
  )
  (:durative-action durActionName
    :parameters (?aa)
    :duration ()
    :condition ()
    :effect ()
  )
  (:derived (pred ?aa) (predB ?aa))
)