(define (problem problemName)
  (:domain domainName)
  (:goal (and
           (predA)
           (predB)
           (not (not (predC)))
           (not (predE))
           (= (numFunc) 5)
           (= (objFunc) constA)
           (predF constA)
           (forall (?a) (and (predG ?a) (predH)))
           (predK constA)
           (predL)
           (not (predM))
         )
  )
)