(define (problem problemName)
  (:domain domainName)
  (:init (pred1)
         (pred2 constA)
         (= (numericFunc constA) 2)
         (= (numericFunc constB) 5)
         (= (objectFunc) constA)
  )
)