(define (problem problemName)
  (:domain domainName)
  (:goal (and
           (= (+ 12 13 (-numericFunc))
              (/ (* numericFunc numericFunc) (- 55 numericFunc))
           )
           (= (+ 12 13 (-(numericFunc constA)))
              (/ (* (numericFunc constA) (numericFunc constB)) (- 49 (numericFunc constB)))
           )
           (= (- (numericFunc2 constA))
              (- (numericFunc2 constB))
           )
           (= (- (numericFunc3))
              (+ numericFunc numericFunc3)
           )
           (= (numericFunc4)
              (numericFunc5)
           )
           (= (numericFunc6)
              (numericFunc7)
           )
         )
  )
)