(define (problem problemName)
  (:domain domainName)
  (:init (pred0)
         (pred1 constA) (pred1 constB)
         (pred2 constA constA)
         (pred3 constA constA constA)
         (predA) (predB constA) (predB constB)
  )
)