(define (domain domainName)
  (:requirements :typing :adl :fluents)
  (:constants constA constB)
  (:predicates (predA) (predB) (predC) (predD) (pred1 ?a) (pred2 ?a ?b))
  (:action actionName0
    :parameters (?a)
    :precondition (predA)
    :effect (and (not (predA))
                 (pred1 ?a)
            )
  )
  (:action actionName1
    :parameters (?a ?b)
    :precondition (predB)
    :effect (and (not (predB))
                 (pred2 ?a ?b)
            )
  )
  (:action actionName2
    :parameters ()
    :precondition (predD)
    :effect (predC)
  )
)
