(define (domain domainName)
  (:requirements :durative-actions)
  (:durative-action actionA
    :parameters (?a)
    :duration ()
	:condition ()
    :effect ()
  )
  (:durative-action actionB
    :parameters ()
    :duration ()
	:condition ()
    :effect ()
  )
)